-- ACTS 게시판 반응 기능 STEP 1
-- Supabase > SQL Editor(에스큐엘 에디터) > New query(뉴 쿼리)에 붙여넣고 RUN

create table if not exists public.post_reactions (
  id bigint generated by default as identity primary key,
  post_id text not null,
  reaction_type text not null check (reaction_type in ('pray','amen','support','heart')),
  visitor_id text not null,
  created_at timestamptz not null default now(),
  unique (post_id, reaction_type, visitor_id)
);

create index if not exists post_reactions_post_id_idx
  on public.post_reactions (post_id);

alter table public.post_reactions enable row level security;

drop policy if exists "Public can read reactions" on public.post_reactions;
create policy "Public can read reactions"
on public.post_reactions
for select
to anon, authenticated
using (true);

drop policy if exists "Public can add reactions" on public.post_reactions;
create policy "Public can add reactions"
on public.post_reactions
for insert
to anon, authenticated
with check (
  reaction_type in ('pray','amen','support','heart')
  and length(visitor_id) between 8 and 120
  and length(post_id) between 1 and 120
);

drop policy if exists "Public can remove own browser reactions" on public.post_reactions;
create policy "Public can remove own browser reactions"
on public.post_reactions
for delete
to anon, authenticated
using (true);

-- 참고: 이 반응은 로그인 없는 공개형 1단계 기능입니다.
-- 같은 브라우저에서는 visitor_id를 LocalStorage에 저장해 중복 반응을 방지합니다.
-- 향후 회원 로그인 기능을 붙이면 auth.uid() 기반 정책으로 더 강하게 제한할 수 있습니다.
